[package]
name = "async-borrow"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"

[dev-dependencies]
tokio = { features=["rt", "macros", "time"], version="1.43.0" }
tokio-macros = "1.*"